name: firebase_dart_ui.example
description: Firebase UI wrapper Example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.15.0 <2.0.0'

dependencies:
  angular:  ^5.0.0-alpha+5
  firebase: ^4.3.0
  firebase_dart_ui:
    path: ../../firebase_dart_ui


dev_dependencies:
  build_runner: ^0.7.10+1
  build_web_compilers: ^0.3.0
  webdriver: ^1.2.1
  # todo: Why is this needed?
  barback: any

