name: firebase_dart_ui
description: An Angular Dart wrapper for Firebase UI.
version: 0.0.1
homepage: https://github.com/wstrange/firebase_dart_ui
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=2.0.0-dev.15.0 <2.0.0'

dependencies:
  angular:  ^5.0.0-alpha+2
  firebase: ^4.2.0+1
  js: ^0.6.0
  func: "^1.0.0"

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
#
#dependency_overrides:
#  # Necessary with angular: 5.0.0-alpha+1 dependency.
#  analyzer: ^0.31.0-alpha.1
#
transformers:
- angular:
    entry_points:
      - example/web/main.dart
- dart_to_js_script_rewriter
