name: firebase_dart_ui
description: An Angular Dart wrapper for Firebase UI.
version: 0.0.2
homepage: https://github.com/wstrange/firebase_dart_ui
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=2.0.0-dev.23.0 <2.0.0'

dependencies:
  angular:  ^5.0.0-alpha+5
  firebase: ^4.3.1
  js: ^0.6.0
  func: "^1.0.0"

dev_dependencies:
  build_runner: ^0.7.10
  build_web_compilers: ^0.3.0
  webdriver: ^1.2.1

